# Generated by Django 5.0 on 2025-10-02 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shopping_center_name', models.CharField(db_index=True, help_text='Unique identifier for the shopping center', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=2, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('total_gla', models.IntegerField(blank=True, help_text='Total Gross Leasable Area in square feet', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('center_type', models.CharField(blank=True, help_text='Shopping center type (can be calculated later from GLA)', max_length=50, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('property_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('leasing_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('leasing_brokerage', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for Google Maps display', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for Google Maps display', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Shopping Center',
                'verbose_name_plural': 'Shopping Centers',
                'db_table': 'shopping_centers',
                'ordering': ['shopping_center_name'],
                'indexes': [models.Index(fields=['shopping_center_name'], name='shopping_ce_shoppin_e5aff2_idx'), models.Index(fields=['address_city', 'address_state'], name='shopping_ce_address_73e55a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(db_index=True, help_text='Business name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_suite_number', models.CharField(blank=True, help_text='Suite/unit number', max_length=50, null=True)),
                ('square_footage', models.IntegerField(blank=True, help_text='Leased square footage', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('retail_category', models.CharField(blank=True, help_text='Retail category/type', max_length=100, null=True)),
                ('base_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Base rent amount', max_digits=10, null=True)),
                ('lease_term', models.IntegerField(blank=True, help_text='Lease term in months', null=True)),
                ('lease_commence', models.DateField(blank=True, help_text='Lease commencement date', null=True)),
                ('lease_expiration', models.DateField(blank=True, help_text='Lease expiration date', null=True)),
                ('credit_category', models.CharField(blank=True, help_text='Credit rating category', max_length=50, null=True)),
                ('categories', models.CharField(blank=True, help_text='Additional categories', max_length=255, null=True)),
                ('shopping_center', models.ForeignKey(help_text='Shopping center where this tenant is located', on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.shoppingcenter')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['shopping_center', 'tenant_suite_number'],
                'indexes': [models.Index(fields=['tenant_name'], name='tenants_tenant__d17221_idx'), models.Index(fields=['shopping_center', 'tenant_name'], name='tenants_shoppin_7f40b2_idx')],
            },
        ),
    ]
