# Generated by Django 5.0 on 2025-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='categories',
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='zoning_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ownership_type',
            field=models.CharField(blank=True, help_text='Ownership type', max_length=100, null=True),
        ),
    ]
