# Generated by Django 5.0 on 2025-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_tenant_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='major_group',
            field=models.CharField(blank=True, choices=[('anchors_majors', 'Anchors & Majors'), ('inline_retail', 'Inline Retail'), ('food_beverage', 'Food & Beverage'), ('services', 'Services'), ('entertainment_leisure', 'Entertainment / Leisure'), ('other_nonretail', 'Other / Non-Retail'), ('seasonal_popup', 'Seasonal / Pop-Up'), ('vacant', 'Vacant')], db_index=True, help_text='High-level tenant categorization for tenant mix analysis', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='retail_category',
            field=models.CharField(blank=True, help_text='Retail category/type (subcategory)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['major_group'], name='tenants_major_g_56c83b_idx'),
        ),
    ]
