# Generated by Django 5.0 on 2025-10-08 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_tenant_major_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcenter',
            name='center_type',
            field=models.CharField(blank=True, help_text='ICSC property type classification (determined by GLA thresholds)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Decimal degrees, populated by geocoding service', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Decimal degrees, populated by geocoding service', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='shopping_center_name',
            field=models.CharField(help_text='Primary identifier - must be unique', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='total_gla',
            field=models.IntegerField(blank=True, help_text='Gross Leasable Area in square feet', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='base_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly base rent', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_commence',
            field=models.DateField(blank=True, help_text='Lease start date', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='major_group',
            field=models.CharField(blank=True, choices=[('anchors_majors', 'Anchors & Majors'), ('inline_retail', 'Inline Retail'), ('food_beverage', 'Food & Beverage'), ('services', 'Services'), ('entertainment_leisure', 'Entertainment / Leisure'), ('other_nonretail', 'Other / Non-Retail'), ('seasonal_popup', 'Seasonal / Pop-Up'), ('vacant', 'Vacant')], help_text='High-level tenant categorization for tenant mix analysis', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ownership_type',
            field=models.CharField(blank=True, help_text='Owned vs Leased', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='retail_category',
            field=models.CharField(blank=True, help_text='Specific retail business category (from taxonomy)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='shopping_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.shoppingcenter'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_name',
            field=models.CharField(help_text='Business/brand name', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_suite_number',
            field=models.CharField(blank=True, help_text='Suite/unit number within shopping center', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='shoppingcenter',
            index=models.Index(fields=['county'], name='shopping_ce_county_181657_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcenter',
            index=models.Index(fields=['center_type'], name='shopping_ce_center__7e90d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('shopping_center', 'tenant_name'), name='unique_tenant_per_center'),
        ),
    ]
