# Generated by Django 5.0 on 2025-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_update_retail_category_mapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenant',
            name='unique_tenant_per_center',
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_name', 'Vacant'), _negated=True), fields=('shopping_center', 'tenant_name'), name='unique_tenant_per_center'),
        ),
    ]
