# Generated by Django 5.0 on 2025-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_fix_vacant_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenant',
            name='unique_tenant_per_center',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='base_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Annual rent per square foot (CRE standard quoting: '$30/SF' means $30/SF/year)", max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('shopping_center', 'tenant_name', 'tenant_suite_number'), name='unique_tenant_per_center'),
        ),
    ]
